/* Disable results caching */
set enable_result_cache_for_session to off;

/* TPC_H  Query 11 - Important Stock Indentification */
set query_group='RSPERF TPC-H 1.11';

SELECT	/* sql-11 */ TOP 100000 PS_PARTKEY,
	SUM(PS_SUPPLYCOST*PS_AVAILQTY)	AS VALUE
FROM	PARTSUPP,
	SUPPLIER,
	NATION
WHERE	PS_SUPPKEY	= S_SUPPKEY	AND
	S_NATIONKEY	= N_NATIONKEY	AND
	N_NAME		= 'SAUDI ARABIA'
GROUP	BY	PS_PARTKEY
HAVING	SUM(PS_SUPPLYCOST*PS_AVAILQTY) >
		(	SELECT	SUM(PS_SUPPLYCOST*PS_AVAILQTY) * 0.0000000333
			FROM	PARTSUPP,
				SUPPLIER,
				NATION
			WHERE	PS_SUPPKEY	= S_SUPPKEY	AND
				S_NATIONKEY	= N_NATIONKEY	AND
				N_NAME		= 'SAUDI ARABIA'
		)
ORDER	BY	VALUE	DESC
;