stages: # List of stages for jobs, and their order of execution
  - build

build-cli-wizard: # Builds cli-wizard using latest nodejs image
  stage: build
  image: node:latest
  script:
    - echo "Compiling the code..."
    - cd benchmarking-tool/cli-wizard
    - npm install
    - npm run build
    - echo "Compile complete."
  cache:
    paths:
      - benchmarking-tool/cli-wizard/node_modules/

build-ui-wizard: # Builds ui-wizard using latest nodejs image
  stage: build
  image: node:latest
  script:
    - echo "Compiling the code..."
    - cd benchmarking-tool/ui-wizard
    - touch src/aws-exports.js # File created by Amplify pull in future
    - npm install
    - npm run build
    - echo "Compile complete."
  cache:
    paths:
      - benchmarking-tool/ui-wizard/node_modules/