stages: # List of stages for jobs, and their order of execution
  - build
  - deploy

build-cdk: # Builds cdk using latest nodejs image
  stage: build
  image: node:latest
  script:
    - echo "Compiling the code..."
    - cd benchmarking-tool/cdk-stack
    - npm install
    - echo "Compile complete."
  cache:
    paths:
      - benchmarking-tool/cdk-stack/node_modules/

build-cli-wizard: # Builds cli-wizard using latest nodejs image
  stage: build
  image: node:latest
  script:
    - echo "Compiling the code..."
    - cd benchmarking-tool/cli-wizard
    - npm install
    - npm run build
    - echo "Compile complete."
  cache:
    paths:
      - benchmarking-tool/cli-wizard/node_modules/

build-ui-wizard: # Builds ui-wizard using latest nodejs image
  stage: build
  image: node:latest
  script:
    - echo "Compiling the code..."
    - cd benchmarking-tool/ui-wizard
    - touch src/aws-exports.js # File created by Amplify pull in future
    - npm install
    - npm run build
    - echo "Compile complete."
  cache:
    paths:
      - benchmarking-tool/ui-wizard/node_modules/

deploy-analytics-004:
  stage: deploy
  image: node:latest
  script:
    - echo "Deploy to analytics account 004 server"
    - cd benchmarking-tool/cdk-stack
    - npm install
    - npm install aws-cdk
    - ./node_modules/aws-cdk/bin/cdk deploy BenchmarkingStack
  environment:
    name: staging
    url: https://isengard.amazon.com/federate?account=$ANALYTICS_ACCOUNT&role=Admin
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH