stages: # List of stages for jobs, and their order of execution
  - build
  - deploy

build-cdk: # Builds cdk using latest nodejs image
  stage: build
  image: node:latest
  script:
    - echo "Compiling the code..."
    - cd source/cdk-stack
    - npm install
    - echo "Compile complete."
  cache:
    paths:
      - source/cdk-stack/node_modules/

build-cli-wizard: # Builds cli-wizard using latest nodejs image
  stage: build
  image: node:latest
  script:
    - echo "Compiling the code..."
    - cd source/cli-wizard
    - npm install
    - npm run build
    - echo "Compile complete."
  cache:
    paths:
      - source/cli-wizard/node_modules/