{
 "title": "importdashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "STACK_NAME",
    "label": "Stack Name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Redshift CPU Utilization - Area Chart Stacked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "metricName": "CPUUtilization",
     "namespace": "AWS/Redshift",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Redshift Queries Completed Per Seconds - Area Chart Stacked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 8 },
   "targets": [
    {
     "metricName": "QueriesCompletedPerSecond",
     "namespace": "AWS/Redshift",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Redshift Queries RuntimeBreakdown - Bar Charts 100% Stacked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "metricName": "QueryRuntimeBreakdown",
     "namespace": "AWS/Redshift",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Bar Charts Benchmarking RunTime Millis - Bar Chart 100% Stacked",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 24 },
   "targets": [
    {
     "dimensions": { "STACK_NAME": "$STACK_NAME" },
     "metricName": "runTimeMillis",
     "namespace": "Benchmarking",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Benchmarking RunTime Millis - Statistics",
   "type": "stat",
   "gridPos": { "h": 16, "w": 22, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "STACK_NAME": "$STACK_NAME" },
     "metricName": "runTimeMillis",
     "namespace": "Benchmarking",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Benchmarking RunTime Millis - Stat",
   "type": "table",
   "gridPos": { "h": 16, "w": 22, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "STACK_NAME": "$STACK_NAME" },
     "metricName": "runTimeMillis",
     "namespace": "Benchmarking",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Minimum"
    }
   ]
  }
 ]
}